### ISSUE TITLE
How about encrypt premium UUID data

### ISSUE THREAD

**Issue by iamyou** [ImpactDevelopment/ImpactServer#35]
After the VAPE database was leaked, some servers adopted a ban on Vape users to prevent cheating. I don't want this to happen on Impact.
(And there was a plugin to check whether the player is the donor of cheat clients,if yes,it will warn.

**Comment by LeafHacker** [comment]
If you are referring to the UUID list's on the Resources repo, iirc they had been removed, although it might make sense to also delete the repo history (but anyone could have already cloned the history due to how git works)

If you are referring to the legacy lists, then this isn't possible because that defeats the purpose of those lists: support for older Impact clients that don't know about the new hashed UUID system. This is why the `Enable legacy` toggle exists.

**Comment by iamyou** [comment]
> If you are referring to the UUID list's on the Resources repo, iirc they had been removed, although it might make sense to also delete the repo history (but anyone could have already cloned the history due to how git works)
> 
> If you are referring to the legacy lists, then this isn't possible because that defeats the purpose of those lists: support for older Impact clients that don't know about the new hashed UUID system. This is why the `Enable legacy` toggle exists.

Thank you,
I noticed that the authentication in client has changed.
